apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-namespace
resources:
  - ../../base
  - configmap-local.yaml
  - be-minio-httpRoute.yaml
  - postgres-pvc.yaml
  - minio-pvc.yaml
