apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: be-minio-route
  namespace: minio-namespace
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "300m"
spec:
  parentRefs:
    - name: global-gateway
      namespace: gateway-namespace
  hostnames:
    - minio.s4v3.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: minio
          port: 9000
