apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-route
  namespace: be-minio
spec:
  parentRefs:
    - name: kong
      namespace: default  # Pointing to the Kong Gateway in default namespace
  hostnames:
    - "minio.s4v3.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: minio
          port: 9000