apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-minio
spec:
  capacity:
    storage: "10Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/storage_k8s/keycloak
    server: 192.168.188.16

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-postgres
spec:
  capacity:
    storage: "5Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/storage_k8s/keycloak
    server: 192.168.188.16
